# Change these first
owner: dev-sidem # Your GitHub organization or username, where this repository lives
repo: status-pages # The name of this repository

sites:
  - name: Kajabi
    url:  https://myinnercircle.yannicktchoum.com/
  - name: aisstable
    url: https://mka.thetchoum.com/
  - name: gohighlevel
    url: https://app.thetchoum.com/
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://www.fr.thetchoumgroup.com/wp-content/themes/tchoum/images/logo-white.png
  name: Statut des services
  introTitle: "Tableau de bord de statut pour les services web"
  introMessage: Statut en temps réel des services web et APIs
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
notifications:
  - type: email
    email: dembenan2019@gmail.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
